spring:
  application:
    name: config-service
    #\u7801\u4E91\u4ED3\u5E93\u6258\u7BA1\u914D\u7F6E
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zxp_173951428/springcloud_family_config
          username: 173951428@qq.com
          password: zxp173951428
          timeout: 5
          default-label: master

server:
  port: 9100

#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

