server:
  port: 8781


#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: order-service
    # 加入redis服务
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 2000
# feign 默认hystrix，新版本降级熔断保护默认是关闭的，需要手动开启
feign:
  hystrix:
    enabled: true

# 设置hystrix 超时时间为4秒，这个设置必须设置好，此设置大于feign 的超时时间，用到hystrix 必须配置好，很重要
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000