spring :
  datasource :
      url : jdbc:mysql://127.0.0.1:3306/sbp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username : root
      password : root
      hikari:
        maxLifetime: 1765000
        maximumPoolSize: 15